<?php

// http://localhost/bmn/api/barang
// http://localhost/bmn/api/barangall

// import library dari REST_Controller
require APPPATH . 'libraries/REST_Controller.php';

// extends class dari REST_Controller
class Api extends REST_Controller
{

  // constructor
  public function __construct($config = 'rest')
  {
    header("Access-Control-Allow-Headers: *");
    header("Access-Control-Allow-Methods: *");
    header("Access-Control-Allow-Origin: *");
    // header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");
    // header("Content-Type: application/json; charset=UTF-8");
    // header("Access-Control-Allow-Methods: POST");
    // header("Access-Control-Max-Age: 3600");
    // header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");
 
    // header('Access-Control-Allow-Origin: *');
    // header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
    // header('Access-Control-Allow-Origin: *');
    // header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method");
    // header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
    
    parent::__construct();
    $this->load->model('apimodel');
  }
  public function users_post()
    {
        // $this->some_model->update_user( ... );
        $message = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('name'),
            'email' => $this->post('email'),
            'message' => 'Added a resource'
        ];
        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }

  public function index_get()
  {

    // testing response
    $response['status'] = 200;
    $response['error'] = false;
    $response['message'] = 'Hai from response';

    // tampilkan response
    $this->response($response);
  }
  public function barang_get()
  {
    //  $id = '46333812'; //id NFC
    $id = $this->get('id');
    if(!$id){
        // $this->response([]);
      $this->response(array('status' => 'fail', 502));
    }
    $query = $this->db->query("select * from barang a, kategoribarang b, ruangan c where a.kodebarang = b.kodebarang and a.koderuangan=c.koderuangan and a.nfctag='" . $id . "'");
    $r =  $query->result_array();
    if ($r) {
      $this->response($r, 200);
    } else {
      $this->response(array('status' => 'fail', 502));
    //  $this->response([]);
    }
  }

  public function barangall_get()
  {
    $r = $this->apimodel->readall();
    $this->response($r);
  }

  public function barang_post()
  {
    $data = array(
      'kodebarang'          => $this->post('kodebarang'),
      'tanggalperoleh'    => $this->post('tanggalperoleh'),
      'merk'    => $this->post('merk'),
      'nup'    => $this->post('nup'),
      'koderuangan'    => $this->post('koderuangan'),
      'keterangan'    => $this->post('keterangan'),
      'nfctag'    => $this->post('nfctag')
    );
    $insert = $this->db->insert('barang', $data);
    if ($insert) {
      $this->response($data, 200);
    } else {
      $this->response(array('status' => 'fail', 502));
    }
  }
  function love_post() {
        $data = array(
                    'id'           => $this->post('id'));
      $this->response($data, 200);
      
      
  }
  function love_put() {
        $data = array('id' => $this->put('id'));
        $this->response($data);
      
  }

  public function kodebarang_get()
  {
    $query = $this->db->query("select * from kategoribarang");
    $r =  $query->result_array();
    if ($r) {
      $this->response($r, 200);
    } else {
      $this->response(array('status' => 'fail', 502));
    }
  }
  public function ruangan_get()
  {
    $query = $this->db->query("select * from ruangan");
    $r =  $query->result_array();
    if ($r) {
      $this->response($r, 200);
    } else {
      $this->response(array('status' => 'fail', 502));
    }
  }
}
